const PRODUCTS = [
    {
        id: 'paldean-fates-etb',
        title: 'Scarlet & Violet: Paldean Fates — Elite Trainer Box',
        brand: 'Pokémon TCG',
        price: 54.95,
        oldPrice: null,
        badge: 'preorder',
        image: 'https://images.pokemontcg.io/sv4pt5/1_hires.png',
        category: 'sealed',
        set: 'Paldean Fates',
        type: 'Box',
        condition: null,
        description: 'De Paldean Fates Elite Trainer Box bevat 9 booster packs, energiekaarten, spelersgids, dobbelstenen en damage counters. Perfect voor collectors die op jacht zijn naar Shiny Pokémon.',
        inStock: true,
        maxQty: 12,
        buttonLabel: 'Pre-order'
    },
    {
        id: 'pikachu-crown-zenith',
        title: 'Pikachu — Crown Zenith (Secret Rare) — Near Mint',
        brand: 'Pokémon singles',
        price: 21.50,
        oldPrice: 25.00,
        badge: 'sale',
        image: 'https://images.pokemontcg.io/swsh12pt5/160_hires.png',
        category: 'single',
        set: 'Crown Zenith',
        type: 'Secret Rare',
        condition: 'Near Mint',
        description: 'Iconische Pikachu Secret Rare uit Crown Zenith. Kaart is direct uit pack gehaald en zorgvuldig in een sleeve + toploader verpakt.',
        inStock: true,
        maxQty: 5,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'charizard-ex-obsidian',
        title: 'Charizard ex — Obsidian Flames (Illustration Rare)',
        brand: 'Pokémon singles',
        price: 89.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/sv3/223_hires.png',
        category: 'single',
        set: 'Obsidian Flames',
        type: 'Illustration Rare',
        condition: 'Near Mint',
        description: 'De meest gezochte Illustration Rare uit Obsidian Flames. Prachtige artwork en sterke spelwaarde in competitieve decks.',
        inStock: true,
        maxQty: 2,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'mew-ex-151',
        title: 'Mew ex — Pokémon 151 (Special Illustration Rare)',
        brand: 'Pokémon singles',
        price: 74.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/sv3pt5/205_hires.png',
        category: 'single',
        set: 'Pokémon 151',
        type: 'Special Illustration Rare',
        condition: 'Near Mint',
        description: 'Special Illustration Rare Mew ex uit de geliefde 151-set. Een must-have voor elke Kanto-collector.',
        inStock: true,
        maxQty: 3,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'umbreon-vmax-evolving',
        title: 'Umbreon VMAX — Evolving Skies (Alternate Art)',
        brand: 'Pokémon singles',
        price: 249.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/swsh7/215_hires.png',
        category: 'single',
        set: 'Evolving Skies',
        type: 'Alternate Art',
        condition: 'Near Mint',
        description: 'De legendarische "Moonbreon" Alternate Art. Eén van de meest iconische kaarten uit het Sword & Shield tijdperk.',
        inStock: true,
        maxQty: 1,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'lucario-vstar-crown',
        title: 'Lucario VSTAR — Crown Zenith (Galarian Gallery)',
        brand: 'Pokémon singles',
        price: 12.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/swsh12pt5/90_hires.png',
        category: 'single',
        set: 'Crown Zenith',
        type: 'Galarian Gallery',
        condition: 'Near Mint',
        description: 'Prachtige Galarian Gallery kaart met gedetailleerde artwork. Betaalbaar instapje in premium Crown Zenith singles.',
        inStock: true,
        maxQty: 8,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'gardevoir-ex-sv',
        title: 'Gardevoir ex — Scarlet & Violet (Special Illustration Rare)',
        brand: 'Pokémon singles',
        price: 18.50,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/sv1/245_hires.png',
        category: 'single',
        set: 'Scarlet & Violet',
        type: 'Special Illustration Rare',
        condition: 'Near Mint',
        description: 'Gardevoir ex SIR met adembenemende illustratie. Populair in zowel collecties als competitieve Gardevoir-ex decks.',
        inStock: true,
        maxQty: 6,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'blastoise-base-set',
        title: 'Blastoise — Base Set (Holo Rare)',
        brand: 'Pokémon singles',
        price: 145.00,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/base1/2_hires.png',
        category: 'single',
        set: 'Base Set',
        type: 'Holo Rare',
        condition: 'Lightly Played',
        description: 'Vintage Blastoise Holo uit de originele Base Set. Licht gespeeld met mooie holografische glans — een echte nostalgie-hit.',
        inStock: true,
        maxQty: 1,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'pokemon-151-booster',
        title: 'Pokémon 151 — Booster Pack',
        brand: 'Pokémon TCG',
        price: 6.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/sv3pt5/1_hires.png',
        category: 'sealed',
        set: 'Pokémon 151',
        type: 'Booster',
        condition: null,
        description: 'Sealed booster pack uit de Pokémon 151 serie. Kans op reverse holo\'s, ex-kaarten en zeldzame illustration rares.',
        inStock: true,
        maxQty: 36,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'paradox-rift-bb',
        title: 'Scarlet & Violet: Paradox Rift — Booster Box',
        brand: 'Pokémon TCG',
        price: 139.95,
        oldPrice: 159.95,
        badge: 'sale',
        image: 'https://images.pokemontcg.io/sv4/1_hires.png',
        category: 'sealed',
        set: 'Paradox Rift',
        type: 'Booster Box',
        condition: null,
        description: 'Factory sealed booster box met 36 packs. Bevat Ancient en Future Pokémon met krachtige ex-kaarten.',
        inStock: true,
        maxQty: 4,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'temporal-forces-etb',
        title: 'Scarlet & Violet: Temporal Forces — Elite Trainer Box',
        brand: 'Pokémon TCG',
        price: 49.95,
        oldPrice: null,
        badge: 'preorder',
        image: 'https://images.pokemontcg.io/sv5/1_hires.png',
        category: 'sealed',
        set: 'Temporal Forces',
        type: 'Box',
        condition: null,
        description: 'Pre-order de Temporal Forces ETB met exclusieve promo-kaart, sleeves en een complete spelset voor two-player battles.',
        inStock: true,
        maxQty: 8,
        buttonLabel: 'Pre-order'
    },
    {
        id: 'rayquaza-vmax-evolving',
        title: 'Rayquaza VMAX — Evolving Skies (Alternate Art)',
        brand: 'Pokémon singles',
        price: 189.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/swsh7/218_hires.png',
        category: 'single',
        set: 'Evolving Skies',
        type: 'Alternate Art',
        condition: 'Near Mint',
        description: 'Adembenemende Rayquaza VMAX Alternate Art met dramatische luchtscene. Top-tier chase kaart uit Evolving Skies.',
        inStock: true,
        maxQty: 2,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'giratina-vstar-lost-origin',
        title: 'Giratina VSTAR — Lost Origin (Alternate Art)',
        brand: 'Pokémon singles',
        price: 65.00,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/swsh11/186_hires.png',
        category: 'single',
        set: 'Lost Origin',
        type: 'Alternate Art',
        condition: 'Near Mint',
        description: 'Giratina VSTAR met unieke distorted artwork. Populair bij zowel spelers als display-collectors.',
        inStock: true,
        maxQty: 4,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'miraidon-ex-sv',
        title: 'Miraidon ex — Scarlet & Violet Base (Special Illustration Rare)',
        brand: 'Pokémon singles',
        price: 22.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/sv1/244_hires.png',
        category: 'single',
        set: 'Scarlet & Violet',
        type: 'Special Illustration Rare',
        condition: 'Near Mint',
        description: 'Futuristische Miraidon ex SIR met neon-accenten. Sterke spelkaart én eyecatcher in elke binder.',
        inStock: true,
        maxQty: 5,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'dragon-shield-sleeves',
        title: 'Matte Black Standard Size Sleeves (100 stuks)',
        brand: 'Dragon Shield',
        price: 10.95,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/base1/2_hires.png',
        imageOpacity: 0.55,
        category: 'accessory',
        set: null,
        type: 'Sleeves',
        condition: null,
        description: 'Premium matte black sleeves van Dragon Shield. Non-glare finish, perfect voor tournament play en dagelijks gebruik.',
        inStock: true,
        maxQty: 20,
        buttonLabel: 'In winkelwagen'
    },
    {
        id: 'charizard-base-set',
        title: 'Charizard — Base Set (Holo Rare)',
        brand: 'Pokémon singles',
        price: 425.00,
        oldPrice: null,
        badge: null,
        image: 'https://images.pokemontcg.io/base1/4_hires.png',
        category: 'single',
        set: 'Base Set',
        type: 'Holo Rare',
        condition: 'Moderately Played',
        description: 'De koning van vintage Pokémon. Base Set Charizard Holo in moderately played conditie — een droom voor elke 90\'s collector.',
        inStock: true,
        maxQty: 1,
        buttonLabel: 'In winkelwagen'
    }
];

function getProductById(id) {
    return PRODUCTS.find(p => p.id === id) || null;
}

function formatEuro(amount) {
    return '€' + amount.toFixed(2).replace('.', ',');
}
